import json
from pathlib import Path

from .models import ResolvedChain, RuntimeConfig


def write_json(path: Path, content: object) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(content, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return path


def chain_document(resolved: ResolvedChain) -> dict:
    chain = resolved.chain
    settings = resolved.profile.relayer
    return {
        "chain": {
            "@type": "/relayer.chains.tendermint.config.ChainConfig",
            "key": resolved.account.name,
            "chain_id": chain.chain_id,
            "rpc_addr": chain.rpc_addr,
            "account_prefix": resolved.profile.account_prefix,
            "gas_adjustment": settings.gas_adjustment,
            "gas_prices": settings.gas_prices,
            "average_block_time_msec": settings.average_block_time_msec,
            "max_retry_for_commit": settings.max_retry_for_commit,
        },
        "prover": {
            "@type": "/relayer.chains.tendermint.config.ProverConfig",
            "trusting_period": settings.trusting_period,
            "refresh_threshold_rate": {
                "numerator": 2,
                "denominator": 3,
            },
        },
    }


def render_chain_files(
    runtime: RuntimeConfig,
    chains: tuple[ResolvedChain, ...],
) -> tuple[Path, ...]:
    destinations = []
    for resolved in chains:
        destination = runtime.runtime_dir / "chains" / f"{resolved.chain.name}.json"
        destinations.append(write_json(destination, chain_document(resolved)))
    return tuple(destinations)


def path_name(source: str, destination: str) -> str:
    prefix = "xrplevm-"
    if source.startswith(prefix) and destination.startswith(prefix):
        return (
            f"{prefix}{source.removeprefix(prefix)}-"
            f"{destination.removeprefix(prefix)}"
        )
    return f"{source}-{destination}"


def path_document(source: ResolvedChain, destination: ResolvedChain) -> dict:
    endpoint = {
        "client-id": "",
        "connection-id": "",
        "channel-id": "",
        "port-id": "transfer",
        "order": "unordered",
        "version": "ics20-1",
    }
    return {
        "src": {"chain-id": source.chain.chain_id, **endpoint},
        "dst": {"chain-id": destination.chain.chain_id, **endpoint},
        "strategy": {"type": "naive"},
    }


def render_path_file(
    runtime: RuntimeConfig,
    name: str,
    source: ResolvedChain,
    destination: ResolvedChain,
) -> Path:
    return write_json(
        runtime.runtime_dir / "paths" / f"{name}.json",
        path_document(source, destination),
    )


def compose_text(runtime: RuntimeConfig) -> str:
    default_runtime = (runtime.root_dir / "runtime").resolve()
    root = json.dumps(".")
    runtime_source = (
        "./runtime"
        if runtime.runtime_dir == default_runtime
        else runtime.runtime_dir.as_posix()
    )
    runtime_dir = json.dumps(runtime_source)
    image = json.dumps(runtime.image)
    container = json.dumps(runtime.container_name)
    network = json.dumps(runtime.network_name)
    ip = json.dumps(runtime.ip)
    return f"""# Generated by main.py. Do not edit manually.
name: yui-relayer-module

services:
  yui-relayer:
    image: {image}
    build:
      context: {root}
      dockerfile: Dockerfile
    container_name: {container}
    entrypoint: ["sleep"]
    command: ["infinity"]
    restart: unless-stopped
    volumes:
      - type: bind
        source: {runtime_dir}
        target: /root/.yui-relayer
    networks:
      interoperability:
        ipv4_address: {ip}
    healthcheck:
      test: ["CMD-SHELL", "test -x /usr/local/bin/yrly"]
      interval: 5s
      timeout: 3s
      retries: 10

networks:
  interoperability:
    name: {network}
    external: true
"""


def render_compose(runtime: RuntimeConfig) -> Path:
    runtime.runtime_dir.mkdir(parents=True, exist_ok=True)
    runtime.compose_file.write_text(compose_text(runtime), encoding="utf-8")
    return runtime.compose_file
