// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: relayer/chains/fabric/config/config.proto

package fabric

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ChainConfig struct {
	ChainId              string               `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ChannelId            string               `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ChaincodeName        string               `protobuf:"bytes,3,opt,name=chaincode_name,json=chaincodeName,proto3" json:"chaincode_name,omitempty"`
	GatewayEndpoint      string               `protobuf:"bytes,4,opt,name=gateway_endpoint,json=gatewayEndpoint,proto3" json:"gateway_endpoint,omitempty"`
	TlsCaCertPath        string               `protobuf:"bytes,5,opt,name=tls_ca_cert_path,json=tlsCaCertPath,proto3" json:"tls_ca_cert_path,omitempty"`
	GatewayHostOverride  string               `protobuf:"bytes,6,opt,name=gateway_host_override,json=gatewayHostOverride,proto3" json:"gateway_host_override,omitempty"`
	MspId                string               `protobuf:"bytes,7,opt,name=msp_id,json=mspId,proto3" json:"msp_id,omitempty"`
	CertPath             string               `protobuf:"bytes,8,opt,name=cert_path,json=certPath,proto3" json:"cert_path,omitempty"`
	KeyPath              string               `protobuf:"bytes,9,opt,name=key_path,json=keyPath,proto3" json:"key_path,omitempty"`
	MspInfos             []*MSPInfoConfig     `protobuf:"bytes,10,rep,name=msp_infos,json=mspInfos,proto3" json:"msp_infos,omitempty"`
	ChaincodeInfo        *ChaincodeInfoConfig `protobuf:"bytes,11,opt,name=chaincode_info,json=chaincodeInfo,proto3" json:"chaincode_info,omitempty"`
	AverageBlockTimeMsec uint64               `protobuf:"varint,12,opt,name=average_block_time_msec,json=averageBlockTimeMsec,proto3" json:"average_block_time_msec,omitempty"`
}

func (m *ChainConfig) Reset()         { *m = ChainConfig{} }
func (m *ChainConfig) String() string { return proto.CompactTextString(m) }
func (*ChainConfig) ProtoMessage()    {}
func (*ChainConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_f83193f67f0901a4, []int{0}
}
func (m *ChainConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ChainConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ChainConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ChainConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainConfig.Merge(m, src)
}
func (m *ChainConfig) XXX_Size() int {
	return m.Size()
}
func (m *ChainConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ChainConfig proto.InternalMessageInfo

type ProverConfig struct {
	TrustingPeriodSec int64 `protobuf:"varint,1,opt,name=trusting_period_sec,json=trustingPeriodSec,proto3" json:"trusting_period_sec,omitempty"`
	MaxClockDriftSec  int64 `protobuf:"varint,2,opt,name=max_clock_drift_sec,json=maxClockDriftSec,proto3" json:"max_clock_drift_sec,omitempty"`
}

func (m *ProverConfig) Reset()         { *m = ProverConfig{} }
func (m *ProverConfig) String() string { return proto.CompactTextString(m) }
func (*ProverConfig) ProtoMessage()    {}
func (*ProverConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_f83193f67f0901a4, []int{1}
}
func (m *ProverConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProverConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProverConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProverConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProverConfig.Merge(m, src)
}
func (m *ProverConfig) XXX_Size() int {
	return m.Size()
}
func (m *ProverConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ProverConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ProverConfig proto.InternalMessageInfo

// MSPInfoConfig aponta pros bytes já serializados do msp.MSPConfig e, opcionalmente, de uma
// política de assinatura da própria MSP (ApplicationPolicy)  espera, só como caminho de
// arquivo em vez de bytes embutidos no JSON de config.
type MSPInfoConfig struct {
	MspId      string `protobuf:"bytes,1,opt,name=msp_id,json=mspId,proto3" json:"msp_id,omitempty"`
	ConfigPath string `protobuf:"bytes,2,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	PolicyPath string `protobuf:"bytes,3,opt,name=policy_path,json=policyPath,proto3" json:"policy_path,omitempty"`
}

func (m *MSPInfoConfig) Reset()         { *m = MSPInfoConfig{} }
func (m *MSPInfoConfig) String() string { return proto.CompactTextString(m) }
func (*MSPInfoConfig) ProtoMessage()    {}
func (*MSPInfoConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_f83193f67f0901a4, []int{2}
}
func (m *MSPInfoConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MSPInfoConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MSPInfoConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MSPInfoConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MSPInfoConfig.Merge(m, src)
}
func (m *MSPInfoConfig) XXX_Size() int {
	return m.Size()
}
func (m *MSPInfoConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_MSPInfoConfig.DiscardUnknown(m)
}

var xxx_messageInfo_MSPInfoConfig proto.InternalMessageInfo

// ChaincodeInfoConfig identifica o cc_ibc (T30) e sua política de
// endosso/IBC vigentes.
type ChaincodeInfoConfig struct {
	Path                  string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name                  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version               string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	EndorsementPolicyPath string `protobuf:"bytes,4,opt,name=endorsement_policy_path,json=endorsementPolicyPath,proto3" json:"endorsement_policy_path,omitempty"`
	IbcPolicyPath         string `protobuf:"bytes,5,opt,name=ibc_policy_path,json=ibcPolicyPath,proto3" json:"ibc_policy_path,omitempty"`
}

func (m *ChaincodeInfoConfig) Reset()         { *m = ChaincodeInfoConfig{} }
func (m *ChaincodeInfoConfig) String() string { return proto.CompactTextString(m) }
func (*ChaincodeInfoConfig) ProtoMessage()    {}
func (*ChaincodeInfoConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_f83193f67f0901a4, []int{3}
}
func (m *ChaincodeInfoConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ChaincodeInfoConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ChaincodeInfoConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ChaincodeInfoConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChaincodeInfoConfig.Merge(m, src)
}
func (m *ChaincodeInfoConfig) XXX_Size() int {
	return m.Size()
}
func (m *ChaincodeInfoConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ChaincodeInfoConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ChaincodeInfoConfig proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ChainConfig)(nil), "relayer.chains.fabric.config.ChainConfig")
	proto.RegisterType((*ProverConfig)(nil), "relayer.chains.fabric.config.ProverConfig")
	proto.RegisterType((*MSPInfoConfig)(nil), "relayer.chains.fabric.config.MSPInfoConfig")
	proto.RegisterType((*ChaincodeInfoConfig)(nil), "relayer.chains.fabric.config.ChaincodeInfoConfig")
}

func init() {
	proto.RegisterFile("relayer/chains/fabric/config/config.proto", fileDescriptor_f83193f67f0901a4)
}

var fileDescriptor_f83193f67f0901a4 = []byte{
	// 640 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0xd1, 0x4e, 0xdb, 0x3c,
	0x14, 0xc7, 0x1b, 0x28, 0xd0, 0x9e, 0xc2, 0x07, 0x9f, 0x0b, 0x22, 0x7c, 0xdf, 0x16, 0xaa, 0x4a,
	0xdb, 0x8a, 0x26, 0x52, 0x8d, 0x89, 0x3d, 0x00, 0xdd, 0x24, 0x7a, 0xc1, 0x56, 0xb5, 0xbb, 0x98,
	0x76, 0x63, 0xb9, 0x8e, 0x9b, 0x58, 0x24, 0x76, 0xe4, 0x98, 0x8e, 0xbe, 0xc5, 0x1e, 0x61, 0x6f,
	0xb1, 0x57, 0xe0, 0x92, 0xcb, 0x5d, 0x6e, 0xf0, 0x22, 0x93, 0xed, 0x14, 0x8a, 0x84, 0xb8, 0x8a,
	0x73, 0xfe, 0xbf, 0xf3, 0x3f, 0xc9, 0x39, 0x47, 0x86, 0x03, 0xc5, 0x52, 0x32, 0x63, 0xaa, 0x4b,
	0x13, 0xc2, 0x45, 0xd1, 0x9d, 0x90, 0xb1, 0xe2, 0xb4, 0x4b, 0xa5, 0x98, 0xf0, 0xb8, 0x7c, 0x84,
	0xb9, 0x92, 0x5a, 0xa2, 0x67, 0x25, 0x1a, 0x3a, 0x34, 0x74, 0x68, 0xe8, 0x98, 0xff, 0xb6, 0x63,
	0x19, 0x4b, 0x0b, 0x76, 0xcd, 0xc9, 0xe5, 0xb4, 0x7f, 0x54, 0xa1, 0xd1, 0x33, 0x78, 0xcf, 0x52,
	0x68, 0x0f, 0x6a, 0x36, 0x1b, 0xf3, 0xc8, 0xf7, 0x5a, 0x5e, 0xa7, 0x3e, 0x5c, 0xb3, 0xef, 0xfd,
	0x08, 0x3d, 0x07, 0xa0, 0x09, 0x11, 0x82, 0xa5, 0x46, 0x5c, 0xb2, 0x62, 0xbd, 0x8c, 0xf4, 0x23,
	0xf4, 0x02, 0xfe, 0xb1, 0x24, 0x95, 0x11, 0xc3, 0x82, 0x64, 0xcc, 0x5f, 0xb6, 0xc8, 0xc6, 0x5d,
	0xf4, 0x23, 0xc9, 0x18, 0x3a, 0x80, 0xad, 0x98, 0x68, 0xf6, 0x8d, 0xcc, 0x30, 0x13, 0x51, 0x2e,
	0xb9, 0xd0, 0x7e, 0xd5, 0x82, 0x9b, 0x65, 0xfc, 0x43, 0x19, 0x46, 0xaf, 0x60, 0x4b, 0xa7, 0x05,
	0xa6, 0x04, 0x53, 0xa6, 0x34, 0xce, 0x89, 0x4e, 0xfc, 0x15, 0xe7, 0xa9, 0xd3, 0xa2, 0x47, 0x7a,
	0x4c, 0xe9, 0x01, 0xd1, 0x09, 0x3a, 0x82, 0x9d, 0xb9, 0x67, 0x22, 0x0b, 0x8d, 0xe5, 0x94, 0x29,
	0xc5, 0x23, 0xe6, 0xaf, 0x5a, 0xba, 0x59, 0x8a, 0xa7, 0xb2, 0xd0, 0x9f, 0x4a, 0x09, 0xed, 0xc0,
	0x6a, 0x56, 0xe4, 0xe6, 0x4f, 0xd6, 0x2c, 0xb4, 0x92, 0x15, 0x79, 0x3f, 0x42, 0xff, 0x43, 0xfd,
	0xbe, 0x58, 0xcd, 0x2a, 0x35, 0x3a, 0xaf, 0xb3, 0x07, 0xb5, 0x73, 0x36, 0x73, 0x5a, 0xdd, 0x35,
	0xe7, 0x9c, 0xcd, 0xac, 0x74, 0x0a, 0x75, 0x6b, 0x27, 0x26, 0xb2, 0xf0, 0xa1, 0xb5, 0xdc, 0x69,
	0x1c, 0xbd, 0x0e, 0x9f, 0x9a, 0x47, 0x78, 0x36, 0x1a, 0xf4, 0xc5, 0x44, 0xba, 0xbe, 0x0f, 0x6b,
	0xa6, 0xbc, 0x49, 0x46, 0x5f, 0x16, 0xfb, 0x68, 0xfc, 0xfc, 0x46, 0xcb, 0xeb, 0x34, 0x8e, 0xde,
	0x3c, 0x6d, 0xd7, 0x9b, 0xe7, 0x2c, 0x98, 0xde, 0xb7, 0xde, 0x04, 0xd1, 0x31, 0xec, 0x92, 0x29,
	0x53, 0x24, 0x66, 0x78, 0x9c, 0x4a, 0x7a, 0x8e, 0x35, 0xcf, 0x18, 0xce, 0x0a, 0x46, 0xfd, 0xf5,
	0x96, 0xd7, 0xa9, 0x0e, 0xb7, 0x4b, 0xf9, 0xc4, 0xa8, 0x9f, 0x79, 0xc6, 0xce, 0x0a, 0x46, 0xdb,
	0x19, 0xac, 0x0f, 0x94, 0x69, 0x69, 0xb9, 0x22, 0x21, 0x34, 0xb5, 0xba, 0x28, 0x34, 0x17, 0x31,
	0xce, 0x99, 0xe2, 0x32, 0xc2, 0xc6, 0xc2, 0x6c, 0xcb, 0xf2, 0xf0, 0xdf, 0xb9, 0x34, 0xb0, 0xca,
	0x88, 0x51, 0x74, 0x08, 0xcd, 0x8c, 0x5c, 0x62, 0x6a, 0x4b, 0x46, 0x8a, 0x4f, 0xb4, 0xe5, 0x97,
	0x2c, 0xbf, 0x95, 0x91, 0xcb, 0x9e, 0x51, 0xde, 0x1b, 0x61, 0xc4, 0x68, 0x3b, 0x81, 0x8d, 0x07,
	0xad, 0x59, 0x98, 0x94, 0xb7, 0x38, 0xa9, 0x7d, 0x68, 0xb8, 0x5f, 0x77, 0xf3, 0x70, 0xfb, 0x08,
	0x2e, 0x64, 0x47, 0xb2, 0x0f, 0x8d, 0x5c, 0xa6, 0x9c, 0x96, 0x03, 0x73, 0xdb, 0x08, 0x2e, 0x64,
	0x80, 0xf6, 0x4f, 0x0f, 0x9a, 0x8f, 0xb4, 0x0d, 0x21, 0xa8, 0xda, 0x0c, 0x57, 0xce, 0x9e, 0x4d,
	0xcc, 0xee, 0xb4, 0x2b, 0x63, 0xcf, 0xc8, 0x87, 0xb5, 0x29, 0x53, 0x05, 0x97, 0xa2, 0x34, 0x9f,
	0xbf, 0xa2, 0x77, 0xb0, 0xcb, 0x44, 0x24, 0x55, 0xc1, 0x32, 0x26, 0x34, 0x5e, 0xfc, 0x0c, 0xb7,
	0xeb, 0x3b, 0x0b, 0xf2, 0xe0, 0xee, 0x8b, 0xd0, 0x4b, 0xd8, 0xe4, 0x63, 0xfa, 0x80, 0x2f, 0x17,
	0x9e, 0x8f, 0xe9, 0x3d, 0x77, 0x32, 0xba, 0xfa, 0x13, 0x54, 0xae, 0x6e, 0x02, 0xef, 0xfa, 0x26,
	0xf0, 0x7e, 0xdf, 0x04, 0xde, 0xf7, 0xdb, 0xa0, 0x72, 0x7d, 0x1b, 0x54, 0x7e, 0xdd, 0x06, 0x95,
	0xaf, 0xc7, 0x31, 0xd7, 0xc9, 0xc5, 0x38, 0xa4, 0x32, 0xeb, 0x2a, 0x4e, 0xc4, 0x94, 0xa4, 0x94,
	0x08, 0xc2, 0x49, 0x97, 0xd3, 0xc3, 0xd9, 0x05, 0x3f, 0x7c, 0xf4, 0x4a, 0x19, 0xaf, 0xda, 0x1b,
	0xe1, 0xed, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xf1, 0x58, 0xc2, 0x72, 0x04, 0x00, 0x00,
}

func (m *ChainConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChainConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ChainConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AverageBlockTimeMsec != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.AverageBlockTimeMsec))
		i--
		dAtA[i] = 0x60
	}
	if m.ChaincodeInfo != nil {
		{
			size, err := m.ChaincodeInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintConfig(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x5a
	}
	if len(m.MspInfos) > 0 {
		for iNdEx := len(m.MspInfos) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MspInfos[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintConfig(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.KeyPath) > 0 {
		i -= len(m.KeyPath)
		copy(dAtA[i:], m.KeyPath)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.KeyPath)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.CertPath) > 0 {
		i -= len(m.CertPath)
		copy(dAtA[i:], m.CertPath)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.CertPath)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.MspId) > 0 {
		i -= len(m.MspId)
		copy(dAtA[i:], m.MspId)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.MspId)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.GatewayHostOverride) > 0 {
		i -= len(m.GatewayHostOverride)
		copy(dAtA[i:], m.GatewayHostOverride)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.GatewayHostOverride)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.TlsCaCertPath) > 0 {
		i -= len(m.TlsCaCertPath)
		copy(dAtA[i:], m.TlsCaCertPath)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.TlsCaCertPath)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.GatewayEndpoint) > 0 {
		i -= len(m.GatewayEndpoint)
		copy(dAtA[i:], m.GatewayEndpoint)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.GatewayEndpoint)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ChaincodeName) > 0 {
		i -= len(m.ChaincodeName)
		copy(dAtA[i:], m.ChaincodeName)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.ChaincodeName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ChannelId) > 0 {
		i -= len(m.ChannelId)
		copy(dAtA[i:], m.ChannelId)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.ChannelId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ProverConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProverConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProverConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxClockDriftSec != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.MaxClockDriftSec))
		i--
		dAtA[i] = 0x10
	}
	if m.TrustingPeriodSec != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.TrustingPeriodSec))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MSPInfoConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MSPInfoConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MSPInfoConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PolicyPath) > 0 {
		i -= len(m.PolicyPath)
		copy(dAtA[i:], m.PolicyPath)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.PolicyPath)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ConfigPath) > 0 {
		i -= len(m.ConfigPath)
		copy(dAtA[i:], m.ConfigPath)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.ConfigPath)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MspId) > 0 {
		i -= len(m.MspId)
		copy(dAtA[i:], m.MspId)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.MspId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ChaincodeInfoConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChaincodeInfoConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ChaincodeInfoConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.IbcPolicyPath) > 0 {
		i -= len(m.IbcPolicyPath)
		copy(dAtA[i:], m.IbcPolicyPath)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.IbcPolicyPath)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.EndorsementPolicyPath) > 0 {
		i -= len(m.EndorsementPolicyPath)
		copy(dAtA[i:], m.EndorsementPolicyPath)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.EndorsementPolicyPath)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Version) > 0 {
		i -= len(m.Version)
		copy(dAtA[i:], m.Version)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.Version)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Path) > 0 {
		i -= len(m.Path)
		copy(dAtA[i:], m.Path)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.Path)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintConfig(dAtA []byte, offset int, v uint64) int {
	offset -= sovConfig(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ChainConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.ChannelId)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.ChaincodeName)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.GatewayEndpoint)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.TlsCaCertPath)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.GatewayHostOverride)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.MspId)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.CertPath)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.KeyPath)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	if len(m.MspInfos) > 0 {
		for _, e := range m.MspInfos {
			l = e.Size()
			n += 1 + l + sovConfig(uint64(l))
		}
	}
	if m.ChaincodeInfo != nil {
		l = m.ChaincodeInfo.Size()
		n += 1 + l + sovConfig(uint64(l))
	}
	if m.AverageBlockTimeMsec != 0 {
		n += 1 + sovConfig(uint64(m.AverageBlockTimeMsec))
	}
	return n
}

func (m *ProverConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TrustingPeriodSec != 0 {
		n += 1 + sovConfig(uint64(m.TrustingPeriodSec))
	}
	if m.MaxClockDriftSec != 0 {
		n += 1 + sovConfig(uint64(m.MaxClockDriftSec))
	}
	return n
}

func (m *MSPInfoConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MspId)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.ConfigPath)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.PolicyPath)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	return n
}

func (m *ChaincodeInfoConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Path)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.EndorsementPolicyPath)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.IbcPolicyPath)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	return n
}

func sovConfig(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozConfig(x uint64) (n int) {
	return sovConfig(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ChainConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChainConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChainConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChaincodeName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChaincodeName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GatewayEndpoint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GatewayEndpoint = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TlsCaCertPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TlsCaCertPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GatewayHostOverride", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GatewayHostOverride = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MspId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MspId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CertPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CertPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeyPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MspInfos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MspInfos = append(m.MspInfos, &MSPInfoConfig{})
			if err := m.MspInfos[len(m.MspInfos)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChaincodeInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ChaincodeInfo == nil {
				m.ChaincodeInfo = &ChaincodeInfoConfig{}
			}
			if err := m.ChaincodeInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AverageBlockTimeMsec", wireType)
			}
			m.AverageBlockTimeMsec = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AverageBlockTimeMsec |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProverConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProverConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProverConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustingPeriodSec", wireType)
			}
			m.TrustingPeriodSec = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TrustingPeriodSec |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxClockDriftSec", wireType)
			}
			m.MaxClockDriftSec = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxClockDriftSec |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MSPInfoConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MSPInfoConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MSPInfoConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MspId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MspId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConfigPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConfigPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PolicyPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ChaincodeInfoConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChaincodeInfoConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChaincodeInfoConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Path", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Path = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndorsementPolicyPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EndorsementPolicyPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcPolicyPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IbcPolicyPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipConfig(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthConfig
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupConfig
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthConfig
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthConfig        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowConfig          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupConfig = fmt.Errorf("proto: unexpected end of group")
)
